#+TITLE: CV Rainer M. Krug
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+DATE: \today

#+AUTHOR: Rainer M. Krug
#+EMAIL: Rainer@krugs.de
#+LANGUAGE: en

:LATEX:
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER:
#+LATEX_HEADER_EXTRA:
#+LATEX_COMPILER: pdflatex
#+LaTeX_HEADER: \usepackage{rmk_org_cv}
:END:

:OPTIONS:
#+OPTIONS: toc:nil H:10 ':t
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t  |:t tags:nil
:END:

#+SELECT_TAGS: export
#+EXCLUDE_TAGS: old

#+CREATOR: Emacs 25.1.1 (Org mode 8.3.6)



* COMMENT Copy bibliographies from Mendeley Folder 
#+begin_src sh :results output :eval never-export
  cp ~/Documents/Mendeley/My_publications* ./
#+end_src

#+RESULTS:



* Personal Details
** Name 
Rainer M. Krug
** Address
Le Petit Plessis 1B \\
78730 Longvilliers \\
France
** Telephone
+33 9 53 10 27 44
** Mobile
+33 6 85 62 59 98
** Fax
+33 9 53 10 27 44
** E-mail
Rainer@krugs.de
** Year of birth
1968
** Civil status
married, one daughter

* Qualifications
  :PROPERTIES:
  :CUSTOM_ID: qualifications
  :END:

** Postgraduate
   :PROPERTIES:
   :CUSTOM_ID: postgraduate
   :END:

** 2008 
*PhD in Conservation Ecology*, Stellenbosch University, South Africa

Thesis Title: Modelling seed dispersal in restoration and biological
invasion.

** 1997
*MSc Conservation Biology*, University of Cape Town, South Africa

Thesis topic: The Genetic Diversity in a Founded Population of the
African buffalo (/Syncerus caffer/): an example of an Artificial
Bottleneck.

** 1995 
*Diplom (MSc equivalent) in Physics*, Philips-Universität Marburg, Germany

Thesis Title: Der Einfluss von Habitat Heterogenität auf die mittlere
Überlebensdauer von Populationen (The influence of habitat heterogeneity
on the mean survival time of populations)\\
Subjects for oral examination: Experimental Physics, Theoretical
Physics, Ecological Modelling, Biology

** Undergraduate
   :PROPERTIES:
   :CUSTOM_ID: undergraduate
   :END:

   
** 1992
*Vor-Diplom (BSc equivalent) in physics*, Philips-Universität Marburg, Germany

Subjects for oral examination: Experimental Physics, Theoretical
Physics, Mathematics, Chemistry.

* Positions held
  :PROPERTIES:
  :CUSTOM_ID: work-experience
  :END:
** 08/2015 -- 09/2015 
*Laboratoire Ecologie, Systematique et Evolution, Paris Sud* 

Postdoctoral Researcher
# Paris Sud, Contrat No. 063-2015

** 11/2014 -- 12/2014  
*Laboratoire Ecologie, Systematique et Evolution, Paris Sud* 

Postdoctoral Researcher
# CNRS, Contrat No. 5012023

** 09/2013 -- 11/2013
*Laboratoire Ecologie, Systematique et Evolution, Paris Sud*

Postdoctoral Researcher
# Paris Sud, Contrat No. 078-2013

** 08/2011 -- \nbsp{}\nbsp{}\nbsp{}\nbsp{}\nbsp{}\nbsp{}\nbsp{}\nbsp{}\nbsp{}\nbsp{}\nbsp{}
*DST-NRF Centre of Excellence for Invasion Biology, Stellenbosch University*

Research Associate

** 06/2008 -- 06/2008
*DST-NRF Centre of Excellence for Invasion Biology, Stellenbosch University*

Postdoctoral Research Fellow, hosted by Prof. Dave Richardson.

** 06/2007 -- 06/2008
*Plant Conservation Unit, University of Cape Town* 

Postdoctoral Research Fellow, hosted by Prof. Timm Hoffman.

* Areas of interest and expertise                                     :long:
** Spatial modelling of pattern and processes on regional to local scale

I am interested in ecological modelling, particularly ecological
modelling and its integration and interaction with field experiments and
data. My main interest lies in the field of processes and pattern
description and analysis which processes cause pattern and how pattern
influence the processes. These pattern and processes can range from
population to ecosystem levels.

More specifically, I am interested in the functioning of ecosystems and
the dynamics of populations and communities which processes and
disturbances are essential in maintaining the dynamics? How do they
react to changes in e.g. the frequency or intensity of these processes?
Which processes and disturbances are essential in maintaining certain
pattern in the system? Which role does dispersal play in the maintenance
of these systems?

To answer these questions, it is important to combine field work with
ecological simulation models of different complexity in all stages of
the project from the planning of the experiments to the analysis of the
field data and the identification of important parameter and processes.

** Scenarios and Models on local scales
The combined usage of scenarios and models is a very powerful approach
to assess impacts of changes on properties of the simulated system,
like ecosystem health and functioning or ecosystem services. The main
focus of research involving Scenarios and Models has been on global
and regional scale and aimed ad policy. But the local scale is missing
which gives a wide range of very interesting research topics and
problems. These include scaling from global and regional to local as
on local scale different processes have to be included; local dynamics
which can link global scenarios (e.g. climate change) to effects on
the local scale for populations, communities and ecosystems;
addressing of management questions in the context of different budget
scenarios as well as environmental (e.g. climate change) and social
scenarios (population growth or change in behaviour);

** Linking and implementing simulation models in management and policy
Essential is for me the close integration of theoretical models and
field work and field data. Models can help to plan experiments,
determine sample sizes needed, simplifying experiments. Field
experiments can enhance and simplify models and validate results
obtained in ecosystem models. These simplified but valid models can be
used to address conservation and policy related questions.

To link management into the models developed to be able to provide
applicable feedback to managers, is an important aspect for me, as well
as the close co-operation with managers during all phases of the
project. This approach, coupled with a close co-operation with field
biologists, makes it possible, that the results of the projects are not
only scientifically interesting, but also have an impact on the
management practices.

** Using open source tools to develop models
All my simulation models and analysis use only Open Source software.
This includes R for analysis and writing my simulations, GRASS and
QGIS as GIS programs, which I also use in my simulations (GRASS). This
approach of only using Open Source software, provides the flexibility
to develop the simulation models and analysis protocols, distribute
them freely and to enable others (scientists as well as implementing
agencies like nature conservation agencies) to use and evaluate the
code without limitations and without having to purchased specific
software.

In addition, the use of open source tools and making the code of the
models available enables reproducible research in a way that the same
data can be analysed using the same scripts again at a later stage. 

To make my research even more reproducible and transparent, I started
using virtualisation technologies (Docker) to have the complete
analysis and simulation environment in one container (including
operating system) which can be re-used anytime a re-analysis of the
same or new data becomes necessary.


* Areas of interest and expertise                                       :old:
  :PROPERTIES:
  :CUSTOM_ID: areas-of-interest-and-expertise-long
  :END:

I am interested in ecological modelling, particularly ecological
modelling and its integration and interaction with field experiments and
data. My main interest lies in the field of processes and pattern
description and analysis which processes cause pattern and how pattern
influence the processes. These pattern and processes can range from
population to ecosystem levels.

Essential is for me the close integration of theoretical models and
field work and field data. Models can help to plan experiments,
determine sample sizes needed, simplifying experiments. Field
experiments can enhance and simplify models and validate results
obtained in ecosystem models. These simplified but valid models can be
used to address conservation and policy related questions.

More specifically, I am interested in the functioning of ecosystems and
the dynamics of populations and communities which processes and
disturbances are essential in maintaining the dynamics? How do they
react to changes in e.g. the frequency or intensity of these processes?
Which processes and disturbances are essential in maintaining certain
pattern in the system? Which role does dispersal play in the maintenance
of these systems?

To answer these questions, it is important to combine field work with
ecological simulation models of different complexity in all stages of
the project from the planning of the experiments to the analysis of the
field data and the identification of important parameter and processes.

My PhD focused on the role of seed dispersal in restoration and
biological invasion, the effects of alien vegetation on the
establishment of indigenous species and the effects of biocontrol agents
on the spread of invasive species. This involved developing rule-based
simulation models reflecting the seed dispersal and plant distributions
observed in the field, and making predictions of the spread of species
under different scenarios. The model was written in Delphi.

A recent research focus was on population dynamics and reconstructing
the age structure of populations of /Aloe pillansii/, spatial dynamics
of alien invasive plants and the interaction with different management
strategies, including biocontrol. My latest projects (spatial and
temporal dynamics) combine the field of ecological modelling with
spatial statistics, as the development of simulation models as well as
the comparison of different spatial pattern is essential to them.

To link management into the models developed to be able to provide
applicable feedback to managers, is an important aspect for me, as well
as the close co-operation with managers during all phases of the
project. This approach, coupled with a close co-operation with field
biologists, makes it possible, that the results of the projects are not
only scientifically interesting, but also have an impact on the
management practises.

In the field of statistics, I am interested in resampling methods and I
employed a bootstrapping approach in the analysis of seed dispersal
data. Data arising from the simulations are all analysed in the
statistical package R, using a range of different functions and modules.
I have written numerous scripts in R to aid with data analysis and
presentation. I also wrote a package for R implementing the Earth Movers
Distance based on an implementation in C++ by Haibin Ling and Kazunori
Okada.

All my simulation models and analysis use only Open Source software.
This includes R for analysis and writing my simulations, GRASS and
QGIS as GIS programs, which I also use in my simulations (GRASS). This
approach of only using Open Source software, provides the flexibility
to develop the simulation models and analysis protocols, distribute
them freely and to enable others (scientists as well as implementing
agencies like nature conservation agencies) to use the code without
limitations and without having to purchased specific software.

* Research
  :PROPERTIES:
  :CUSTOM_ID: research
  :END:
** 08/2015 -- 09/2015 
*Laboratoire Ecologie, Systematique et Evolution, Paris Sud* 

Analyze measured vertical wind profiles to improve the performance of
a forest growth model (CASTANEA) in regards to energy balance. 

** 11/2014 -- 12/2014  
*Laboratoire Ecologie, Systematique et Evolution, Paris Sud* 

Develop proof of concept for assessing multi species forest community
productivity. This was done in co-operation with 

** 09/2013 -- 11/2013
*Laboratoire Ecologie, Systematique et Evolution, Paris Sud*

Adapt the framework developed to simulate the alien spread in the
Western Cape for management of invasive alien species in the
Drakensberg in Southern Africa. This included adding of new species
and modification of processes parameter. The final product was a
framework for further development.

** 2008 -- 2012                                                       :long:
*DST-NRF Centre of Excellence for Invasion Biology, Stellenbosch University*

Investigating the temporal dynamics and the spread of biocontrol
agents and their host plants on a landscape scale using a GIS based
ecological simulation model, as well a non-spatial approach to
understand diverse aspects of the interaction between biocontrol agent
and host plant and how these interactions influence the effectiveness
of biocontrol agents in halting the spread of invasive
species. Results from the project were used to inform implementing
agencies and are communicated in the form of contributions to a
handbook.

Modelling the spread of alien species in the Western Cape with the aim
of optimising the alien management strategies. This project included
aspects ranging from using an Analytical Hierarchical Process to capture
and quantify the subjective decision making process of prioritizing,
translating this into a spatial simulation model, developing a
spatial-temporal simulation model which included fire, alien plant
management, different dispersal vectors (wind, water, birds) and to use
high performance computing infrastructure (cluster) to run the
simulations and to develop a package for R to compare the different
resulting prioritisation maps spatially.

Investigating the spread of invasive species under different climate
change scenarios. This involved developing the spread models (population
based as well as probabilistic) which included climatic suitability maps
to project the observed distribution under different climate change
scenarios to identify risk areas and to assess the invasive potential of
these species.

Assessing the viability of pine plantations under different (and
changing) fire regimes using a basic modelling approach.

** 2008 -- 2012                                                      :short:
*DST-NRF Centre of Excellence for Invasion Biology, Stellenbosch University*

Investigating the temporal dynamics and the spread of biocontrol
agents and their host plants on a landscape scale using a GIS based
ecological simulation model. Results from the project were used to
inform implementing agencies and are communicated in the form of
contributions to a handbook.

Modelling the spread of alien species in the Western Cape with the aim
of optimising the alien management strategies. Using an Analytical Hierarchical Process to capture
and quantify the subjective decision making process,
translating this into a spatial simulation model which included fire, alien plant
management and different dispersal vectors (wind, water, birds) modules and to use
high performance computing infrastructure (cluster) for simulations.

Investigating the spread of invasive species under different climate
change scenarios. 

Assessing the viability of pine plantations under different (and
changing) fire regimes using a basic modelling approach.

** 2007 -- 2008
*Plant Conservation Unit, University of Cape Town*

Analyzing the population dynamics of /Aloe pillansii/, a tree aloe, with
focus on the recruitment events and their reconstruction.

** 2000 -- 2007
*Conservation Ecology and Entomology department, Stellenbosch University*

Modelling the role of seed dispersal in restoration and biological
invasion, and investigating factors influencing the spread of a
species.  using a rule-based simulation models based on data and
experts opinions.

** 1996 -- 1997
*Percy FitzPatrick Institute of African Ornithology, University of Cape Town*

Investigated the genetic heterogeneity of three populations of African
Buffalo using microsatellites

GIS based conservation planning exercise in which species presence
absence data was used to identify areas most relevant for conservation.

Participated in analysis of the financial value of the Good Hope
Environmental Education Centre.

** 1995 -- 1995
*Department of Physics, Philipps-Universität Marburg* Developin of a
simulation model focussing on the effect of habitat use on the mean
survival time of populations. In co-operation with a biologist who was
involved in the planning of the project and in the formulation of the
questions.
* Additional skills
  :PROPERTIES:
  :CUSTOM_ID: additional-skills
  :END:

** Computer
   :PROPERTIES:
   :CUSTOM_ID: computer
   :END:

*Operating System* Expert Linux user; advanced Mac and Windows user

*Programming Languages* Extensive experience in programming in R,
Delphi / Pascal; user of LaTeX; basic usage of C

*Programs* Extensive experience in R, GRASS; Daily Emacs user; MS
Office programs / Libre Office; basic experience of QGIS and Arc-GIS

** Language
   :PROPERTIES:
   :CUSTOM_ID: language
   :END:

*German* home language

*English* reading, writing and speaking fluent

*French* reading, writing and speaking fair

* Grants
   :PROPERTIES:
   :CUSTOM_ID: grants
   :END:

** 2009 -- 2010
NRF Freestanding Postdoctoral Fellowship awarded

** 1999 -- 2000
Deutscher Akademischer Austauschdienst (DAAD: German Academic Exchange
Service) grant to conduct fieldwork for PhD at Gobabeb, Namibia.

** 1996 -- 1997
Deutscher Akademischer Austauschdienst (DAAD: German Academic Exchange
Service) grant to attend MSc in Conservation Biology course at UCT.

* Teaching Experience
  :PROPERTIES:
  :CUSTOM_ID: teaching-experience
  :END:

** 1997 -- 2007
"Introduction to True Basic", a one-week introductory course to the
ecological modelling module as part of the MSc Conservation Biology at
the University of Cape Town. For the same course, I assisted in
lecturing the module "Ecological Modelling" for three years.

** 2004
Seven week course including assignments on models in ecology as part
of the BWE 424 course in the Department of Conservation Ecology, as
well as additional lectures on models in ecology, and I regularly
assisted in teaching Leslie Matrix modelling in a module on
sustainable harvesting.

In addition, I taught six practicals for the Population and
Conservation Ecology undergraduate course at the Stellenbosch
University.

During my PhD I co-supervised an MSc student who investigated seed
dispersal in Renosterveld by conducting seed trapping experiments. 

** 2007, 2008 and 2009
R introductory R block courses to students from postgraduate to
postdoctoral level (between 2 and 3 days each).

** 2008 and 2009
Involved in conducting the Tygerberg Olympiad, a project for grade
nine to eleven learners, in which they are taught aspects ranging from
ecological, legal, archeological aspects concerning the region
(Tygerberg). At the end, they are expected to give a short
presentation and prices are handed out.

* Other Experience
  :PROPERTIES:
  :CUSTOM_ID: other-experience
  :END:

During my time at the desert research station Gobabeb (1997 2000), I was
involved in conducting participatory workshops with the local
communities on fog harvesting and sustainable use of the nara fruit.

* Publications
  :PROPERTIES:
  :CUSTOM_ID: publications
  :END:
#+BEGIN_EXPORT latex
\titlespacing{\subsection}
            {0.4\textwidth}% max width of the title(for wrap/leftmargin shape)
            {5pt}% vertical space before the title
            {15pt}% separation between title and text
#+END_EXPORT
** Peer-reviewed Journals
   :PROPERTIES:
   :CUSTOM_ID: peer-reviewed-journals
   :END:
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-PeerReviewedArticles}
\btPrintAll
\end{btSect}
#+END_EXPORT


** Book Chapters
   :PROPERTIES:
   :CUSTOM_ID: book-chapters
   :END:
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-InBook}
\btPrintAll
\end{btSect}
#+END_EXPORT


** Conference proceedings
   :PROPERTIES:
   :CUSTOM_ID: conference-proceedings
   :END:
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-Proceedings}
\btPrintAll
\end{btSect}
#+END_EXPORT


** Conference presentations
   :PROPERTIES:
   :CUSTOM_ID: conference-oral-presentations-first-author-only
   :END:
Only first author, except invited keynote presentations
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-Presentations}
\btPrintAll
\end{btSect}
#+END_EXPORT


** COMMENT Conference poster presentations
First Author only
   :PROPERTIES:
   :CUSTOM_ID: conference-poster-presentations-first-author-only
   :END:
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-Posters}
\btPrintAll
\end{btSect}
#+END_EXPORT


** Software Packages
   :PROPERTIES:
   :CUSTOM_ID: software-packages
   :END:
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-Software}
\btPrintAll
\end{btSect}
#+END_EXPORT


** Guest lectures
   :PROPERTIES:
   :CUSTOM_ID: guest-lectures
   :END:
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-GuestLectures}
\btPrintAll
\end{btSect}
#+END_EXPORT



