#+TITLE: CV Rainer M. Krug
#+EMAIL: Rainer@krugs.de
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+DATE: \today

#+AUTHOR: Rainer M. Krug
#+EMAIL: Rainer@krugs.de
#+LANGUAGE: en

:LATEX:
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+LATEX_HEADER:
#+LATEX_HEADER_EXTRA:
#+LATEX_COMPILER: pdflatex
#+LaTeX_HEADER: \usepackage{rmk_org_cv}
:END:

:OPTIONS:
#+OPTIONS: toc:nil H:10 ':t
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t  |:t tags:nil
:END:

#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport

#+CREATOR: Emacs 25.1.1 (Org mode 8.3.6)



* COMMENT Copy bibliographies from Mendeley Folder 
#+begin_src sh :results output :eval never-export
  cp ~/Documents/Mendeley/My_publications* ./
#+end_src

#+RESULTS:



* Personal Details
** Name 
Rainer M. Krug
** Address
Le Petit Plessis 1B \\
78730 Longvilliers \\
France
** Telephone
+33 9 53 10 27 44
** Mobile
+33 6 85 62 59 98
** Fax
+33 9 53 10 27 44
** E-mail
Rainer@krugs.de
** Date of birth
12 April 1968
** Civil status
married, one daughter

* Qualifications
  :PROPERTIES:
  :CUSTOM_ID: qualifications
  :END:

** Postgraduate
   :PROPERTIES:
   :CUSTOM_ID: postgraduate
   :END:

** 2008 
*PhD in Conservation Ecology*, Stellenbosch University, South Africa

Thesis Title: Modelling seed dispersal in restoration and biological
invasion.

** 1997
*MSc Conservation Biology*, University of Cape Town, South Africa

Thesis topic: The Genetic Diversity in a Founded Population of the
African buffalo (/Syncerus caffer/): an example of an Artificial
Bottleneck.

** 1995 
*Diplom (MSc equivalent) in Physics*, Philips-Universität Marburg, Germany

Thesis Title: Der Einfluss von Habitat Heterogenität auf die mittlere
Überlebensdauer von Populationen (The influence of habitat heterogeneity
on the mean survival time of populations)\\
Subjects for oral examination: Experimental Physics, Theoretical
Physics, Ecological Modelling, Biology

** Undergraduate
   :PROPERTIES:
   :CUSTOM_ID: undergraduate
   :END:

   
** 1992
*Vor-Diplom (BSc equivalent) in physics*, Philips-Universität Marburg, Germany

Subjects for oral examination: Experimental Physics, Theoretical
Physics, Mathematics, Chemistry.

* Positions held
  :PROPERTIES:
  :CUSTOM_ID: work-experience
  :END:
** 10/2016 -- 12/2016 
*Laboratoire Ecologie, Systematique et Evolution, Paris Sud* 

Researcher
# Paris Sud, TO ENTER

** 08/2015 -- 09/2015 
*Laboratoire Ecologie, Systematique et Evolution, Paris Sud* 

Postdoctoral Researcher
# Paris Sud, Contrat No. 063-2015

** 11/2014 -- 12/2014  
*Laboratoire Ecologie, Systematique et Evolution, Paris Sud* 

Postdoctoral Researcher
# CNRS, Contrat No. 5012023

** 09/2013 -- 11/2013
*Laboratoire Ecologie, Systematique et Evolution, Paris Sud*

Postdoctoral Researcher
# Paris Sud, Contrat No. 078-2013

** 08/2011 -- 12/2016
*DST-NRF Centre of Excellence for Invasion Biology, Stellenbosch University*

Research Associate

** 06/2008 -- 06/2008
*DST-NRF Centre of Excellence for Invasion Biology, Stellenbosch University*

Postdoctoral Research Fellow, hosted by Prof. Dave Richardson.

** 06/2007 -- 06/2008
*Plant Conservation Unit, University of Cape Town* 

Postdoctoral Research Fellow, hosted by Prof. Timm Hoffman.

* Areas of Interest and expertise
** Keywords                                                  :ignoreheading:
Ecological Modelling; statistical computing; combined modelling and
experimental approaches; invasive species management; spatial pattern
analysis; decision support; open source tools

** Details                                                   :ignoreheading:
My research interest and focus is on 1) spatial modeling and analysis
of pattern and processes and their integration with field experiments
and observations, ranging from population (local) to ecosystem
(regional) scale, 2) the impact of change (climate change, human
impacts, alien spread, ...) and conscious human actions (management)
on these pattern and ultimately on the function of these ecosystems
and ecosystem services, and 3) the use of models in decision support
of the management of natural resources.

During my research career I have developed and used different types of
models, ranging from individual based models, over hybrid models using
individual based approaches together with grid based elements, to pure
grid based models. The systems studied ranged from populations and
communities on the local scale to community dynamics (e.g. grassland -
shrubland dynamics, two biocontrol species one invasive species
system, spread of three alien invasive species) on the local scale and
spread simulations of individual species on the national scale under
different climate change scenarios. Most of my research included
different management scenarios in the form of alien plant management
actions.

Nearly all the simulation and analysis tools I use (and used) are Open
Source software (R, GRASS GIS, QGIS). This provides the flexibility to
develop the simulation models and analysis protocols without
additional costs, distribute them freely and to enable others
(scientists as well as implementing agencies like nature conservation
agencies) to use and evaluate the code without limitations and without
having to purchased specific software, i.e. reproducible
research. Reproducible research includes for me to use scripts in
analysis and generation of graphs and to make these as well as the
simulation models available (as far as funder conditions allow this).



* Research Projects
  :PROPERTIES:
  :CUSTOM_ID: research
  :END:
** 10/2016 -- present
Literature Analysis of Scenarios and Models on Global scale (*Laboratoire Ecologie, Systematique et Evolution, Paris Sud*).

** 08/2015 -- 09/2015
Analyze measured vertical wind profiles to improve the performance of
a forest growth model (CASTANEA) in regards to energy balance
(*Laboratoire Ecologie, Systematique et Evolution, Paris Sud*).

** 11/2014 -- 12/2014
Develop proof of concept for assessing multi species forest community
productivity (*Laboratoire Ecologie, Systematique et Evolution, Paris Sud*).

** 09/2013 -- 11/2013
Adapt the framework developed to simulate the alien spread in the
Western Cape for management of invasive alien species in the
Drakensberg in Southern Africa (*Laboratoire Ecologie, Systematique et Evolution, Paris Sud*). 
# This included adding of new species and modification of processes parameter. The final product was a framework for further development.

** 2008 -- 2012                                                       :long:
*DST-NRF Centre of Excellence for Invasion Biology, Stellenbosch University*

Investigating the temporal dynamics and the spread of biocontrol
agents and their host plants on a landscape scale using a GIS based
ecological simulation model, as well a non-spatial approach to
understand diverse aspects of the interaction between biocontrol agent
and host plant and how these interactions influence the effectiveness
of biocontrol agents in halting the spread of invasive
species. Results from the project were used to inform implementing
agencies and are communicated in the form of contributions to a
handbook.

Modelling the spread of alien species in the Western Cape with the aim
of optimising the alien management strategies. This project included
aspects ranging from using an Analytical Hierarchical Process to capture
and quantify the subjective decision making process of prioritizing,
translating this into a spatial simulation model, developing a
spatial-temporal simulation model which included fire, alien plant
management, different dispersal vectors (wind, water, birds) and to use
high performance computing infrastructure (cluster) to run the
simulations and to develop a package for R to compare the different
resulting prioritisation maps spatially.

Investigating the spread of invasive species under different climate
change scenarios. This involved developing the spread models (population
based as well as probabilistic) which included climatic suitability maps
to project the observed distribution under different climate change
scenarios to identify risk areas and to assess the invasive potential of
these species.

Assessing the viability of pine plantations under different (and
changing) fire regimes using a basic modelling approach.

** 2008 -- 2012
Investigating the temporal dynamics and the spread of biocontrol
agents and their host plants on a landscape scale using a GIS based
ecological simulation model. Results from the project were used to
inform implementing agencies and are communicated in the form of
contributions to a handbook (*DST-NRF Centre of Excellence for Invasion Biology, Stellenbosch University*).

Modelling the spread of alien species in the Western Cape with the aim
of optimising the alien management strategies. Using an Analytical Hierarchical Process to capture
and quantify the subjective decision making process,
translating this into a spatial simulation model which included fire, alien plant
management and different dispersal vectors (wind, water, birds) modules and to use
high performance computing infrastructure (cluster) for simulations (*DST-NRF Centre of Excellence for Invasion Biology, Stellenbosch University*).

Investigating the spread of invasive species under different climate
change scenarios (*DST-NRF Centre of Excellence for Invasion Biology, Stellenbosch University*). 

Assessing the viability of pine plantations under different (and
changing) fire regimes using a basic modelling approach (*DST-NRF Centre of Excellence for Invasion Biology, Stellenbosch University*).

** 2007 -- 2008
Analyzing the population dynamics of /Aloe pillansii/, a tree aloe, with
focus on the recruitment events and their reconstruction(*Plant Conservation Unit, University of Cape Town*).

** 2000 -- 2007
Modelling the role of seed dispersal in restoration and biological
invasion, and investigating factors influencing the spread of a
species.  using a rule-based simulation models based on data and
experts opinions (*Conservation Ecology and Entomology department, Stellenbosch University*).

** 1996 -- 1997
Investigated the genetic heterogeneity of three populations of African
Buffalo using microsatellites (*Percy FitzPatrick Institute of African Ornithology, University of Cape Town*).

# GIS based conservation planning exercise in which species presence absence data was used to identify areas most relevant for conservation (*Percy FitzPatrick Institute of African Ornithology, University of Cape Town*).

# Participated in analysis of the financial value of the Good Hope Environmental Education Centre (*Percy FitzPatrick Institute of African Ornithology, University of Cape Town*).

** 1995 -- 1995
Development of an individual based simulation model focussing on the effect of habitat
use on the mean survival time of populations (*Department of Physics,
Philipps-Universität Marburg*).
* Additional skills
  :PROPERTIES:
  :CUSTOM_ID: additional-skills
  :END:

** Computer
   :PROPERTIES:
   :CUSTOM_ID: computer
   :END:

*Operating System* Expert Linux user; advanced Mac and Windows user

*Programming Languages* Extensive experience in programming in R,
Delphi / Pascal; user of LaTeX; basic usage of C

*Programs* Extensive experience in R, GRASS; Daily Emacs user; MS
Office programs / Libre Office; basic experience of QGIS and Arc-GIS

** Language
   :PROPERTIES:
   :CUSTOM_ID: language
   :END:

*German* native language

*English* reading, writing and speaking fluent

*French* reading, writing and speaking fair

* Grants
   :PROPERTIES:
   :CUSTOM_ID: grants
   :END:

** 2009 -- 2010
NRF Freestanding Postdoctoral Fellowship

** 1999 -- 2000
Deutscher Akademischer Austauschdienst (DAAD: German Academic Exchange
Service) grant to conduct fieldwork for PhD at Gobabeb, Namibia.

** 1996 -- 1997
Deutscher Akademischer Austauschdienst (DAAD: German Academic Exchange
Service) grant to attend MSc in Conservation Biology course at UCT.

* Teaching Experience
  :PROPERTIES:
  :CUSTOM_ID: teaching-experience
  :END:


** Postgraduate teaching
# 1997 -- 2007
"Introduction to True Basic", a one-week introductory course to the
ecological modelling module as part of the MSc Conservation Biology at
the University of Cape Town. For the same course, I assisted in
lecturing the module "Ecological Modelling" for three years.

# 2004
Seven week course including assignments on models in ecology as part
of the BWE 424 course in the Department of Conservation Ecology, as
well as additional lectures on models in ecology, and I regularly
assisted in teaching Leslie Matrix modelling in a module on
sustainable harvesting.

# ????
I taught six practicals for the Population and Conservation Ecology
undergraduate course at the Stellenbosch University.
** Student supervision
# 2004
During my PhD I co-supervised an MSc student who investigated seed
dispersal in Renosterveld by conducting seed trapping experiments. 


** Block course
# 2007, 2008 and 2009
R introductory R block courses to students from postgraduate to
postdoctoral level (between 2 and 3 days 

** Other teaching
# 2008 and 2009
Involved in conducting the Tygerberg Olympiad, a project for grade
nine to eleven learners, in which they are taught aspects ranging from
ecological, legal, archeological aspects concerning the region
(Tygerberg). At the end, they are expected to give a short
presentation and prices are handed out.

* Other Experience
  :PROPERTIES:
  :CUSTOM_ID: other-experience
  :END:

During my time at the desert research station Gobabeb (1997 2000), I was
involved in conducting participatory workshops with the local
communities on fog harvesting and sustainable use of the nara fruit.

* Publications
  :PROPERTIES:
  :CUSTOM_ID: publications
  :END:
#+BEGIN_EXPORT latex
\titlespacing{\subsection}
            {0.4\textwidth}% max width of the title(for wrap/leftmargin shape)
            {5pt}% vertical space before the title
            {15pt}% separation between title and text
#+END_EXPORT
** Peer-reviewed Journals
   :PROPERTIES:
   :CUSTOM_ID: peer-reviewed-journals
   :END:
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-PeerReviewedArticles}
\btPrintAll
\end{btSect}
#+END_EXPORT


** Book Chapters
   :PROPERTIES:
   :CUSTOM_ID: book-chapters
   :END:
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-InBook}
\btPrintAll
\end{btSect}
#+END_EXPORT


** Conference proceedings
   :PROPERTIES:
   :CUSTOM_ID: conference-proceedings
   :END:
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-Proceedings}
\btPrintAll
\end{btSect}
#+END_EXPORT


** Conference presentations
   :PROPERTIES:
   :CUSTOM_ID: conference-oral-presentations-first-author-only
   :END:
Only first author, except invited keynote presentations
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-Presentations}
\btPrintAll
\end{btSect}
#+END_EXPORT


** COMMENT Conference poster presentations
First Author only
   :PROPERTIES:
   :CUSTOM_ID: conference-poster-presentations-first-author-only
   :END:
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-Posters}
\btPrintAll
\end{btSect}
#+END_EXPORT


** Software Packages
   :PROPERTIES:
   :CUSTOM_ID: software-packages
   :END:
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-Software}
\btPrintAll
\end{btSect}
#+END_EXPORT


** Guest lectures
   :PROPERTIES:
   :CUSTOM_ID: guest-lectures
   :END:
#+BEGIN_EXPORT latex
\begin{btSect}[elsarticle-harv]{My_publications-GuestLectures}
\btPrintAll
\end{btSect}
#+END_EXPORT



